services:
  app:
    container_name: stockflow-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/stockflow_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    depends_on:
      - db
    restart: unless-stopped

  db:
    container_name: stockflow-db
    image: postgres:16
    ports:
           - "5433:5432"
    environment:
      POSTGRES_DB: stockflow_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - stockflow-db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  stockflow-db-data: