spring.application.name=stockflow
server.port=8080

# PostgreSQL local database.
# If your local PostgreSQL password is different, change only this value.
spring.datasource.url=jdbc:postgresql://localhost:5432/stockflow_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.thymeleaf.cache=false
server.servlet.session.timeout=120m
